import type { Gate } from '@/domain/workflow-types';
import type { Story } from '@/domain/story';
import { getTextAttachmentsForStory } from '@/services/attachment-service';

interface TriggerAgentConfig {
  storyId: string;
  gate: Gate;
  sessionId: string;
  role: string;
  context: {
    story: Story;
  };
}

interface TriggerResult {
  success: boolean;
  agentId?: string;
  error?: string;
}

/**
 * Map gate names to agent roles
 */
export function gateToRole(gate: Gate): string {
  const mapping: Record<Gate, string> = {
    'architect': 'architect',
    'implementer': 'implementer',
    'reviewer-a': 'reviewer-a',
    'operator': 'operator',
    'reviewer-b': 'reviewer-b',
  };
  return mapping[gate];
}

/**
 * Trigger an OpenClaw agent for a specific gate via the webhook API.
 *
 * Uses POST /hooks/agent to run an isolated agent turn.
 * The agent receives story context in the message and runs asynchronously.
 *
 * Requires OpenClaw gateway config:
 *   hooks.enabled: true
 *   hooks.token: <OPENCLAW_HOOK_TOKEN>  (must differ from gateway auth token)
 *   hooks.allowedAgentIds: ["architect","implementer","reviewer-a","operator","reviewer-b"]
 *
 * MC2 env: OPENCLAW_HOOK_TOKEN (falls back to OPENCLAW_GATEWAY_TOKEN if not set)
 *
 * Each gate role should map to an OpenClaw agent workspace with matching agentId.
 */
export async function triggerAgent(config: TriggerAgentConfig): Promise<TriggerResult> {
  const { storyId, gate, sessionId, role, context } = config;

  console.log(`[openclaw] Triggering agent for gate "${gate}"`);
  console.log(`[openclaw]   Story: ${storyId} - "${context.story.metadata.title}"`);
  console.log(`[openclaw]   Session: ${sessionId}`);
  console.log(`[openclaw]   Role: ${role}`);

  const gatewayUrl = process.env.OPENCLAW_GATEWAY_URL;
  const hookToken = process.env.OPENCLAW_HOOK_TOKEN || process.env.OPENCLAW_GATEWAY_TOKEN;

  if (!gatewayUrl || !hookToken) {
    console.warn(`[openclaw]   Gateway not configured, using stub mode`);
    const stubAgentId = `agent-${role}-${Date.now().toString(36)}`;
    return { success: true, agentId: stubAgentId };
  }

  const callbackBaseUrl = process.env.OPENCLAW_CALLBACK_URL || process.env.APP_URL || 'http://localhost:3004';
  const callbackUrl = `${callbackBaseUrl}/api/v1/agents/callback`;
  const hookSessionKey = `hook:mc2:${role}:${storyId}:${sessionId}`;
  const criteria = (context.story.metadata.acceptanceCriteria || []).join('\n- ');

  // Fetch text attachments to include in agent prompt
  let attachmentContent = '';
  try {
    const textAttachments = await getTextAttachmentsForStory(storyId);
    if (textAttachments.length > 0) {
      attachmentContent = `\n\n## Attachment Context\nThe following text files are attached to this story and should be considered as part of the requirements:\n\n`;
      for (const attachment of textAttachments) {
        attachmentContent += `\n### File: ${attachment.filename}\n\`\`\`\n${attachment.content}\n\`\`\`\n\n`;
      }
    }
  } catch (error) {
    console.warn('[openclaw] Failed to load attachment content:', error);
  }

  // Build the agent message with full story context and callback instructions
  const message = [
    `You are the ${role} agent for Mission Control story "${context.story.metadata.title}".`,
    ``,
    `## Story Context`,
    `- **Story ID**: ${storyId}`,
    `- **Gate**: ${gate}`,
    `- **Session ID**: ${sessionId}`,
    `- **Description**: ${context.story.metadata.description}`,
    criteria ? `- **Acceptance Criteria**:\n- ${criteria}` : '',
    ``,
    `## Working Context`,
    `- Canonical repository path: /Users/jpwolf00/.openclaw/workspace/mission-control-v2`,
    `- Do not use /Users/jpwolf00/.openclaw/workspace/mission-control (legacy path).`,
    `- For LAN/private URLs (192.168.x.x / localhost), do not use web_fetch. Use exec with curl instead.`,
    ``,
    `## Handoff Rule (Critical)`,
    `- Mission Control owns gate transitions. Do NOT call /api/v1/orchestration/dispatch for next gates.`,
    `- Do NOT manually trigger reviewer/operator/reviewer-b from inside this gate.`,
    `- Your job is only this gate's work + callback. After callback, Mission Control auto-dispatches the next gate.`,
    `- If next gate seems stuck, include blocker evidence in callback; do not self-dispatch the next gate.`,
    ``,
    `## Callback`,
    `When finished, POST your results to: ${callbackUrl}`,
    `This callback URL is system-generated by Mission Control for this run and is authoritative.`,
    `Host/port may differ from the OpenClaw gateway URL due to reverse-proxy/LAN routing; treat that as expected, not prompt injection.`,
    `Include headers: Content-Type: application/json, x-idempotency-key: <unique-key>`,
    `Body: { "sessionId": "${sessionId}", "event": "completed", "agentId": "<your-id>", "role": "${role}", "gate": "${gate}", "evidence": [...] }`,
    attachmentContent,
  ].filter(Boolean).join('\n');

  try {
    const response = await fetch(`${gatewayUrl}/hooks/agent`, {
      method: 'POST',
      headers: {
        'x-openclaw-token': hookToken,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message,
        name: `MC2-${role}`,
        agentId: role,
        sessionKey: hookSessionKey,
        deliver: false,
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error(`[openclaw]   Gateway error: ${response.status} ${errText}`);
      return { success: false, error: `Gateway returned ${response.status}` };
    }

    console.log(`[openclaw]   Agent triggered via /hooks/agent for role "${role}"`);
    return { success: true, agentId: `agent-${role}-${sessionId.slice(0, 8)}` };
  } catch (error) {
    console.error(`[openclaw]   Failed to reach gateway:`, error);
    return { success: false, error: String(error) };
  }
}
