#!/bin/bash
set -e

echo "🚀 Setting up Mission Control 2.0..."

# Check Node.js version
if ! command -v node &> /dev/null; then
  echo "❌ Node.js not found. Please install Node.js 20+"
  exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
  echo "❌ Node.js 20+ required. Found: $(node -v)"
  exit 1
fi

echo "✅ Node.js $(node -v)"

# Install dependencies
echo "📦 Installing dependencies..."
npm install

# Setup environment
echo "⚙️ Setting up environment..."
if [ ! -f .env ]; then
  if [ -f .env.example ]; then
    # Generate random password
    RANDOM_PASS=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-24)
    cat > .env << EOF
# Database - GENERATED BY SETUP SCRIPT
DB_PASSWORD="$RANDOM_PASS"
DATABASE_URL="postgresql://mc2:$RANDOM_PASS@localhost:5432/mission_control"

# API
NEXT_PUBLIC_API_URL="http://localhost:3000"

# Environment
NODE_ENV=development
EOF
    echo "✅ Created .env with generated password"
    echo "   ⚠️  Review .env file before production use"
  else
    echo "❌ .env.example not found"
    exit 1
  fi
else
  echo "⚠️  .env already exists, skipping"
fi

# Generate Prisma client
echo "🔧 Generating Prisma client..."
npx prisma generate

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "1. Review .env file settings"
echo "2. Start PostgreSQL: docker compose up -d db"
echo "3. Run migrations: npx prisma migrate dev"
echo "4. Start dev server: npm run dev"
echo "5. Open http://localhost:3000"
echo ""
echo "Test all environments:"
echo "  ./scripts/exercise-environments.sh"
echo ""
echo "Deploy to production:"
echo "  ./scripts/deploy-production.sh"